# Based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # required
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Jest
        run: npm run test
      - name: Run TypeScript
        run: npm run typecheck
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.2.0
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CC_TEST_REPORTER_ID: ${{ vars.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
